version: "3"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/data/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  back:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    environment:
      DATABASE_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db

  nginx:
    restart: always
    build:
      context: ./nginx
    volumes:
      - ./front/dist/:/var/www/frontend
    ports:
      - "8080:80"
    depends_on:
      - back

volumes:
  db-data:
