version: "3"

services:
  # db:
  #   image: postgres
  #   volumes:
  #     - db-data:/data/db
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     DATABASE_NAME: ${DATABASE_NAME}
  #     DATABASE_USER: ${DATABASE_USER}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}

  # back:
  #   build:
  #     context: ./back
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./back:/back
  #   env_file: .env
  #   environment:
  #     DATABASE_HOST: db
  #     DATABASE_NAME: ${DATABASE_NAME}
  #     DATABASE_USER: ${DATABASE_USER}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #   depends_on:
  #     - db

  front:
    build:
      context: ./front
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./front:/front

  # nginx:
  #   build:
  #     context: ./nginx
  #   volumes:
  #     - ./back:/static
  #     - ./front:/var/www/frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - back
  #     - front

volumes:
  db-data:
