version: "3"

services:
  db:
    image: postgres
    volumes:
      - db-data:/data/db
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  back:
    build:
      context: ./back
    ports:
      - "8000:8000"
    volumes:
      - ./back:/back
    env_file: .env
    environment:
      DATABASE_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./front/dist/:/var/www/frontend
    ports:
      - "8080:80"
    depends_on:
      - back

volumes:
  db-data:
