version: "3"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/data/db
    ports:
      - "5432:5432"
    env_file:
      - .env

  nginx:
    restart: always
    build:
      context: ./nginx
    volumes:
      - ./front/dist/:/var/www/frontend
    ports:
      - "8080:80"
    depends_on:
      - db

  back:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    env_file:
      - .env
    depends_on:
      - nginx

volumes:
  db-data:
